
project_id = "sqdjqehcxpzsudhzjwbu"

[functions.fetch-staff-members]
verify_jwt = false

[functions.create-staff]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.ai-voice-to-text]
verify_jwt = false

[functions.ai-text-to-voice]
verify_jwt = false
