
project_id = "sqdjqehcxpzsudhzjwbu"

[api]
port = 54321
scheme = "http"

[db]
port = 54322

[studio]
port = 54323

[auth]
enabled = true

[functions.tomtom-geocode]
verify_jwt = false

[functions.get-speechify-api-key]
verify_jwt = false

