
project_id = "sqdjqehcxpzsudhzjwbu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions]
enabled = true
[functions.voice-transcription]
verify_jwt = false
[functions.ai-meeting-summary]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
