
# project configuration
project_id = "sqdjqehcxpzsudhzjwbu"

[api]
# Port to use for the API URL.
port = 54321
scheme = "http"

[db]
# Port to use for the database URL.
port = 54322

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing
[auth]
enabled = true

[functions.tomtom-geocode]
verify_jwt = false

[functions.sync-staff-records]
verify_jwt = true
