
project_id = "lovable-default-project"

[api]
port = 54321
schemas = ["public", "storage", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[storage]
file_size_limit = "50MiB"

# Enable our edge functions
[functions.ai-task-parser]
verify_jwt = true

[functions.get-runware-api-key]
verify_jwt = true

[functions.ai-image-generation]
verify_jwt = true

[functions.ai-meeting-summary]
verify_jwt = true

[functions.voice-transcription]
verify_jwt = true
