
/**
 * Utility functions for exporting meeting summaries
 */

import { formatTime } from '@/utils/audio/audioProcessing';
import html2pdf from 'html2pdf.js';

export interface MeetingSummaryPDFOptions {
  title?: string;
  companyName?: string;
  companyLogo?: string;
  includeFooter?: boolean;
}

/**
 * Exports the meeting summary as a PDF file
 * @param summary The HTML summary content
 * @param duration The meeting duration in seconds
 * @param location Optional meeting location
 * @param attendees Optional list of meeting attendees
 * @param options Additional PDF options
 */
export const exportMeetingSummaryAsPDF = async (
  summary: string,
  duration: number,
  location?: string | null,
  attendees?: string[] | null,
  options: MeetingSummaryPDFOptions = {}
): Promise<void> => {
  // Create PDF content with enhanced styling
  const today = new Date();
  const dateString = today.toLocaleDateString();
  const timeString = today.toLocaleTimeString();
  
  const title = options.title || 'Meeting Summary';
  const companyName = options.companyName || 'WAKTI';
  const includeFooter = options.includeFooter !== false;

  // Extract action items if present
  const actionItemsMatch = summary.match(/##\s*Action Items[^#]*(?=##|$)/i);
  const actionItems = actionItemsMatch ? actionItemsMatch[0]
    .replace(/^##\s*Action Items\s*/i, '')
    .split('\n')
    .filter(line => line.trim().startsWith('-') || line.trim().startsWith('*'))
    .map(item => item.trim().replace(/^[-*]\s*/, ''))
    .join('</li><li>') : '';

  // Process the main content while preserving action items
  const mainContent = summary.replace(/##\s*Action Items[^#]*(?=##|$)/i, '')
    .replace(/\n/g, "<br />")
    .replace(/^## (.*)/gm, '<h2 style="color: #333; margin-top: 20px; margin-bottom: 10px; font-size: 18px;">$1</h2>')
    .replace(/^### (.*)/gm, '<h3 style="color: #444; margin-top: 15px; margin-bottom: 8px; font-size: 16px;">$1</h3>')
    .replace(/^\- (.*)/gm, '<li style="margin-bottom: 5px;">$1</li>')
    .replace(/^\* (.*)/gm, '<li style="margin-bottom: 5px;">$1</li>');

  let pdfContent = `
    <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto;">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
        <div>
          <h1 style="color: #333; margin: 0;">${title}</h1>
          <p style="color: #666; margin: 5px 0;">Generated on ${dateString} at ${timeString}</p>
        </div>
        ${options.companyLogo ? `<img src="${options.companyLogo}" alt="${companyName} Logo" style="height: 60px;">` : ''}
      </div>
      
      <div style="background-color: #f5f5f5; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
        <div style="display: flex; flex-wrap: wrap; gap: 15px;">
          <div style="flex: 1; min-width: 200px;">
            <p style="margin: 5px 0; font-weight: bold;">Duration:</p>
            <p style="margin: 5px 0;">${formatTime(duration)}</p>
          </div>
          
          ${location ? `
          <div style="flex: 1; min-width: 200px;">
            <p style="margin: 5px 0; font-weight: bold;">Location:</p>
            <p style="margin: 5px 0;">${location}</p>
          </div>` : ''}
        </div>
        
        ${attendees && attendees.length > 0 ? `
        <div style="margin-top: 15px;">
          <p style="margin: 5px 0; font-weight: bold;">Attendees:</p>
          <ul style="margin: 5px 0; padding-left: 20px;">
            ${attendees.map(attendee => `<li>${attendee}</li>`).join('')}
          </ul>
        </div>` : ''}
      </div>
      
      ${actionItems ? `
      <div style="background-color: #fff3e0; padding: 15px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #ff9800;">
        <h2 style="color: #e65100; margin: 0 0 10px 0; font-size: 18px;">Action Items</h2>
        <ul style="margin: 0; padding-left: 20px;">
          <li>${actionItems}</li>
        </ul>
      </div>` : ''}
      
      <div style="line-height: 1.6;">
        ${mainContent}
      </div>
      
      ${includeFooter ? `
      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px; text-align: center;">
        <p>Generated by ${companyName} Meeting Summary Tool</p>
      </div>` : ''}
    </div>
  `;

  // Configure PDF options
  const pdfOptions = {
    margin: [15, 15, 15, 15],
    filename: `meeting_summary_${today.toISOString().split('T')[0]}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };
  
  // Generate and download the PDF
  const element = document.createElement('div');
  element.innerHTML = pdfContent;
  document.body.appendChild(element);
  
  try {
    await html2pdf().from(element).set(pdfOptions).save();
  } finally {
    document.body.removeChild(element);
  }
};

/**
 * Creates a download link for audio data
 * @param audioData Audio blob
 * @param filename Filename for the download
 */
export const downloadAudioFile = (audioData: Blob, filename = 'meeting_recording.webm'): void => {
  const url = URL.createObjectURL(audioData);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 100);
};
