// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqdjqehcxpzsudhzjwbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZGpxZWhjeHB6c3VkaHpqd2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjYxNzMsImV4cCI6MjA1NzY0MjE3M30.1YAc8f2wgeMWN-UgoH8tL14aiYme6aTewmWPgfC7j_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);